In [122]:
import pandas as pd

In [123]:
df_raw_fraud_dollars = pd.read_excel(io="fraud.xlsx",sheet_name="Table_1",engine="calamine",skiprows=[0,1,2,4,5,11,12,13],nrows=145)
df_raw_fraud_dollars.drop(columns=["Unnamed: 0"], inplace=True)
df_raw_fraud_dollars = df_raw_fraud_dollars.T
df_fraud_dollars = pd.DataFrame()
for i in df_raw_fraud_dollars:
    itemName = df_raw_fraud_dollars[i][' ']
    if pd.isna(itemName):
        continue
    if itemName.startswith("Last measured"):
        continue
    if itemName.startswith("Benefits"):
        continue
    if itemName.strip() == "":
        continue
    itemName = itemName.split("note")[0]
    df_fraud_dollars = df_fraud_dollars.assign(**{itemName+" Fraud":0,itemName+" Claimant Error":0,itemName+" Official Error":0,itemName+" Total":0,itemName+" Expenditure": 0})
found2024 = False
previousRow = map
df_fraud_dollars["Year"] = []
df_fraud_dollars.set_index("Year", inplace=True)
for row in df_raw_fraud_dollars.itertuples():
    yearName = row[0]
    if yearName.startswith("Unnamed:"):
        previousRow = row
        continue
    if yearName.strip() == "":
        previousRow = row
        continue
    yearName = yearName.split(" ")[1].split("\n")[0]
    if yearName == "2024":
        if not found2024:
            found2024 = True
        else:
            continue
    validColumns = []
    for column in previousRow:
        if not (type(column) is int or type(column) is float or column in ["w","x","z"]):
            continue
        if pd.isna(column):
            continue
        validColumns.append(column)
    df_fraud_dollars.loc[int(yearName)] = validColumns
    previousRow = row
df_fraud_dollars.head()

,All Benefits Fraud,All Benefits Claimant Error,All Benefits Official Error,All Benefits Total,All Benefits Expenditure,Universal Credit Fraud,Universal Credit Claimant Error,Universal Credit Official Error,Universal Credit Total,Universal Credit Expenditure,...,Unreviewed excluding Council Tax Benefit Fraud,Unreviewed excluding Council Tax Benefit Claimant Error,Unreviewed excluding Council Tax Benefit Official Error,Unreviewed excluding Council Tax Benefit Total,Unreviewed excluding Council Tax Benefit Expenditure,Council Tax Benefit Fraud,Council Tax Benefit Claimant Error,Council Tax Benefit Official Error,Council Tax Benefit Total,Council Tax Benefit Expenditure
Year,,,,,,,,,,,,,,,,,,,,,
2025,6500000000,1900000000,1000000000,9500000000,292200000000,5200000000,610000000,540000000,6350000000,65300000000,...,20000000,10000000,10000000,30000000,5400000000,z,z,z,z,z
2024,7300000000,1600000000,800000000,9700000000,266200000000,5620000000,410000000,390000000,6410000000,51900000000,...,470000000,50000000,50000000,570000000,17000000000,z,z,z,z,z
2023,6300000000,1400000000,700000000,8300000000,233800000000,4930000000,290000000,270000000,5500000000,43400000000,...,330000000,60000000,60000000,450000000,15000000000,z,z,z,z,z
2022,6500000000,1500000000,700000000,8700000000,215800000000,5250000000,400000000,270000000,5920000000,40400000000,...,110000000,30000000,20000000,160000000,6600000000,z,z,z,z,z
2021,6200000000,1300000000,800000000,8200000000,211700000000,4880000000,330000000,330000000,5540000000,38200000000,...,140000000,60000000,60000000,260000000,12100000000,z,z,z,z,z

In [124]:
df_raw_fraud_percent = pd.read_excel(io="fraud.xlsx",sheet_name="Table_2",engine="calamine",skiprows=[0,1,2,4,5,11,12,13],nrows=145)
df_raw_fraud_percent.drop(columns=["Unnamed: 0"], inplace=True)
df_raw_fraud_percent = df_raw_fraud_percent.T
df_fraud_percent = pd.DataFrame()
for i in df_raw_fraud_percent:
    itemName = df_raw_fraud_percent[i][' ']
    if pd.isna(itemName):
        continue
    if itemName.startswith("Last measured"):
        continue
    if itemName.startswith("Benefits"):
        continue
    if itemName.strip() == "":
        continue
    itemName = itemName.split("note")[0]
    df_fraud_percent = df_fraud_percent.assign(**{itemName+" Fraud":0,itemName+" Claimant Error":0,itemName+" Official Error":0,itemName+" Total":0})
found2024 = False
previousRow = map
df_fraud_percent["Year"] = []
df_fraud_percent.set_index("Year", inplace=True)
df_fraud_percent
for row in df_raw_fraud_percent.itertuples():
    
    yearName = row[0]
    if yearName.startswith("Unnamed:"):
        previousRow = row
        continue
    if yearName.strip() == "":
        previousRow = row
        continue
    yearName = yearName.split(" ")[1].split("\n")[0]
    if yearName == "2024":
        if not found2024:
            found2024 = True
        else:
            continue
    validColumns = []
    invalidColumns = []
    for column in previousRow:
        if type(column) is str and '*' in column:
            column = float(column.split(' ')[1]) # fixes issue some have with stray "*" or "*'" instances sometimes being part of the excel formatting and sometimes as part of the field
        if not (type(column) is int or type(column) is float or column in ["w","x","z"]):
            invalidColumns.append(column)
            continue
        if pd.isna(column):
            invalidColumns.append(column)
            continue
        validColumns.append(column)
    df_fraud_percent.loc[int(yearName)] = validColumns
    previousRow = row
df_fraud_percent.head()

,All Benefits Fraud,All Benefits Claimant Error,All Benefits Official Error,All Benefits Total,Universal Credit Fraud,Universal Credit Claimant Error,Universal Credit Official Error,Universal Credit Total,State Pension Fraud,State Pension Claimant Error,...,Interdependencies Official Error,Interdependencies Total,Unreviewed excluding Council Tax Benefit Fraud,Unreviewed excluding Council Tax Benefit Claimant Error,Unreviewed excluding Council Tax Benefit Official Error,Unreviewed excluding Council Tax Benefit Total,Council Tax Benefit Fraud,Council Tax Benefit Claimant Error,Council Tax Benefit Official Error,Council Tax Benefit Total
Year,,,,,,,,,,,,,,,,,,,,,
2025,2.2,0.7,0.4,3.3,8.0,0.9,0.8,9.7,w,0.1,...,z,z,0.3,0.2,0.1,0.6,z,z,z,z
2024,2.7,0.6,0.3,3.6,10.8,0.8,0.7,12.4,0.1,0.1,...,z,z,2.8,0.3,0.3,3.4,z,z,z,z
2023,2.7,0.6,0.3,3.6,11.4,0.7,0.6,12.7,w,0.1,...,z,z,2.2,0.4,0.4,3.0,z,z,z,z
2022,3.0,0.7,0.3,4.0,13.0,1.0,0.7,14.7,0,0.1,...,z,z,1.7,0.5,0.3,2.4,z,z,z,z
2021,2.9,0.6,0.4,3.9,12.8,0.9,0.9,14.5,0,0.1,...,z,z,1.1,0.5,0.5,2.2,z,z,z,z

In [125]:
import pandas as pd
import xlrd
import datetime
import re

In [126]:
wb = xlrd.open_workbook("labor.xls")

def xldate_to_str(v, datemode):
    try:
        tup = xlrd.xldate_as_tuple(float(v), datemode)
        if tup[0]:
            return datetime.date(*tup[:3]).isoformat()
    except:
        pass
    try:
        return str(int(float(v)))
    except:
        return str(v).strip()

def is_valid_period(v):
    v = str(v).strip()
    return bool(re.match(
        r"^([A-Za-z]{3}-[A-Za-z]{3}\s+\d{4}"
        r"|[A-Za-z]{3}\s+\d{2,4}"
        r"|[A-Za-z]+\s+\d{4}$"
        r"|\d{4}-\d{2}-\d{2}"
        r"|\d{4}$"
        r"|[A-Z]\d{8,})", v))

def build_col_names(sh, header_rows, ncols):
    raw = []
    for r in header_rows:
        row_vals = [str(sh.cell_value(r, c)).strip() for c in range(ncols)]
        last = ""
        filled = []
        for v in row_vals:
            if v:
                last = v
            filled.append(last)
        raw.append(filled)
    cols = []
    for c in range(ncols):
        parts = []
        for row in raw:
            v = re.sub(r"\s+", " ", row[c]).strip() if c < len(row) else ""
            if v and v not in parts:
                parts.append(v)
        cols.append(" | ".join(parts) if parts else str(c))
    seen = {}
    out = []
    for col in cols:
        if col in seen:
            seen[col] += 1
            out.append(f"{col}_{seen[col]}")
        else:
            seen[col] = 0
            out.append(col)
    return out

def parse_sheet(wb, sheet_name, header_rows, data_start, period_type):
    sh = wb.sheet_by_name(sheet_name)
    cols = build_col_names(sh, header_rows, sh.ncols)
    rows = []
    for r in range(data_start, sh.nrows):
        raw = sh.cell_value(r, 0)
        if period_type == "xldate":
            period = xldate_to_str(raw, wb.datemode)
        elif period_type == "year":
            try:
                period = str(int(float(raw)))
            except:
                period = str(raw).strip()
        else:
            period = str(raw).strip()
        if not is_valid_period(period):
            continue
        rows.append([period] + [sh.cell_value(r, c) for c in range(1, sh.ncols)])
    df = pd.DataFrame(rows, columns=cols)
    df = df.rename(columns={df.columns[0]: "period"})
    df = df.loc[:, (df.columns == "period") | df.notna().any()]
    df = df.set_index("period")
    return df

In [127]:
df_lfs_summary = parse_sheet(wb, "1", [5], 9, "label")
df_lfs_summary.rename(inplace=True,columns={"All aged 16 & over":"16+ Population","Total economically active":"16+ Total Activity Level","Total in employment":"16+ Employment Level","Unemployed":"16+ Unemployment Level","Economically inactive":"16+ Economically Inactive Level","Economic activity":"16+ Economic Activity Rate","Employment":"16+ Employment Rate","Unemployment":"16+ Unemployment Rate","Economic inactivity":"16+ Economic Inactivity Rate","All aged 16 to 64":"16-64 Population","Total economically active_1":"16-64 Total Activity Level","Total in employment_1":"16-64 Employment Level","Unemployed_1":"16-64 Unemployment Level","Economically inactive_1":"16-64 Economically Inactive Level","Economic activity_1":"16-64 Economic Activity Rate","Employment_1":"16-64 Employment Rate","Unemployment_1":"16-64 Unemployment Rate","Economic inactivity_1":"16-64 Economic Inactivity Rate"})
df_lfs_by_age = parse_sheet(wb, "2", [4, 5], 9, "label")
df_ft_pt_temp = parse_sheet(wb, "3", [4, 5], 8, "label")
df_pub_priv_emp = parse_sheet(wb, "4", [4, 5], 9, "year")
df_pub_sec_industry = parse_sheet(wb, "4(1)", [4], 7, "year")
df_workforce_jobs = parse_sheet(wb, "5", [5], 8, "label")
df_jobs_by_industry = parse_sheet(wb, "6", [5], 7, "label")
df_actual_hours = parse_sheet(wb, "7", [5], 9, "label")
df_usual_hours = parse_sheet(wb, "7(1)", [4, 5, 6], 10, "label")
df_unemp_age_duration = parse_sheet(wb, "9", [4, 5, 6], 9, "label")
df_redundancies = parse_sheet(wb, "10", [4, 6], 9, "label")
df_inactivity_reasons = parse_sheet(wb, "11", [4, 5], 9, "label")
df_young_people = parse_sheet(wb, "12", [4, 5], 9, "label")
df_awe_total = parse_sheet(wb, "13", [4, 5, 6], 9, "xldate")
df_awe_bonus = parse_sheet(wb, "14", [4, 5, 6], 9, "xldate")
df_awe_regular = parse_sheet(wb, "15", [4, 5, 6], 9, "xldate")
df_awe_real = parse_sheet(wb, "16", [4, 5, 6], 9, "xldate")
df_labour_disputes = parse_sheet(wb, "18", [5], 7, "label")
df_vacancies_size = parse_sheet(wb, "19", [5], 9, "label")
df_vacancies_unemp = parse_sheet(wb, "20", [6], 8, "label")
df_vacancies_industry = parse_sheet(wb, "21", [6, 7], 11, "label")
df_regional_lfs = parse_sheet(wb, "22", [6, 7, 8], 10, "label")

df_lfs_summary.head()

,16+ Population,16+ Total Activity Level,16+ Employment Level,16+ Unemployment Level,16+ Economically Inactive Level,16+ Economic Activity Rate,16+ Employment Rate,16+ Unemployment Rate,16+ Economic Inactivity Rate,16-64 Population,16-64 Total Activity Level,16-64 Employment Level,16-64 Unemployment Level,16-64 Economically Inactive Level,16-64 Economic Activity Rate,16-64 Employment Rate,16-64 Unemployment Rate,16-64 Economic Inactivity Rate
period,,,,,,,,,,,,,,,,,,
Jan-Mar 1971,40513000.0,25593000.0,24613000.0,980000.0,14919000.0,63.2,60.8,3.8,36.8,33559000.0,25187000.0,24219000.0,967000.0,8373000.0,75.1,72.2,3.8,24.9
Feb-Apr 1971,40531000.0,25573000.0,24575000.0,998000.0,14959000.0,63.1,60.6,3.9,36.9,33565000.0,25172000.0,24187000.0,985000.0,8393000.0,75.0,72.1,3.9,25.0
Mar-May 1971,40550000.0,25582000.0,24559000.0,1023000.0,14968000.0,63.1,60.6,4.0,36.9,33570000.0,25180000.0,24171000.0,1009000.0,8390000.0,75.0,72.0,4.0,25.0
Apr-Jun 1971,40568000.0,25600000.0,24556000.0,1045000.0,14968000.0,63.1,60.5,4.1,36.9,33576000.0,25199000.0,24168000.0,1031000.0,8377000.0,75.1,72.0,4.1,24.9
May-Jul 1971,40587000.0,25603000.0,24541000.0,1062000.0,14984000.0,63.1,60.5,4.1,36.9,33581000.0,25202000.0,24153000.0,1049000.0,8380000.0,75.0,71.9,4.2,25.0

In [128]:
def mergeYearAndRollingPeriods(df_year, df_rolling, rollingOffset):
    yearStart = df_year.index.min()
    df_merged = df_year.copy()
    for i in range(len(df_year)):
        for column in df_rolling.columns:
            #print("Year: "+str(yearStart+i)+" Columns: "+column)
            #print(df_rolling.iloc[12*(i+rollingOffset):12*(i+rollingOffset+1)][column].mean())
            df_merged.loc[yearStart+i,column] = df_rolling.iloc[12*(i+rollingOffset):12*(i+rollingOffset+1)][column].mean()
        #print(12*(i+rollingOffset+1))
    return df_merged

In [129]:
df_fraud_dollars_labour_summary = mergeYearAndRollingPeriods(df_fraud_dollars, df_lfs_summary, 2006-1971)
df_fraud_dollars_labour_summary.head()

,All Benefits Fraud,All Benefits Claimant Error,All Benefits Official Error,All Benefits Total,All Benefits Expenditure,Universal Credit Fraud,Universal Credit Claimant Error,Universal Credit Official Error,Universal Credit Total,Universal Credit Expenditure,...,16+ Economic Inactivity Rate,16-64 Population,16-64 Total Activity Level,16-64 Employment Level,16-64 Unemployment Level,16-64 Economically Inactive Level,16-64 Economic Activity Rate,16-64 Employment Rate,16-64 Unemployment Rate,16-64 Economic Inactivity Rate
Year,,,,,,,,,,,,,,,,,,,,,
2025,6500000000,1900000000,1000000000,9500000000,292200000000,5200000000,610000000,540000000,6350000000,65300000000,...,36.191613,4.330048e+07,3.419484e+07,3.251061e+07,1.684239e+06,9.105636e+06,78.970797,75.081467,4.924607,21.029203
2024,7300000000,1600000000,800000000,9700000000,266200000000,5620000000,410000000,390000000,6410000000,51900000000,...,36.878435,4.298149e+07,3.361839e+07,3.213972e+07,1.478670e+06,9.363106e+06,78.215342,74.775176,4.398237,21.784658
2023,6300000000,1400000000,700000000,8300000000,233800000000,4930000000,290000000,270000000,5500000000,43400000000,...,36.904468,4.256827e+07,3.330745e+07,3.191533e+07,1.392125e+06,9.260815e+06,78.245552,74.975208,4.179604,21.754448
2022,6500000000,1500000000,700000000,8700000000,215800000000,5250000000,400000000,270000000,5920000000,40400000000,...,37.008345,4.212816e+07,3.291196e+07,3.163684e+07,1.275122e+06,9.216198e+06,78.123309,75.096694,3.873985,21.876691
2021,6200000000,1300000000,800000000,8200000000,211700000000,4880000000,330000000,330000000,5540000000,38200000000,...,36.801157,4.179978e+07,3.276337e+07,3.127895e+07,1.484415e+06,9.036413e+06,78.381734,74.830055,4.531172,21.618266

In [130]:
df_fraud_percent_labour_summary = mergeYearAndRollingPeriods(df_fraud_percent, df_lfs_summary, 2006-1971)
df_fraud_percent_labour_summary.head()

,All Benefits Fraud,All Benefits Claimant Error,All Benefits Official Error,All Benefits Total,Universal Credit Fraud,Universal Credit Claimant Error,Universal Credit Official Error,Universal Credit Total,State Pension Fraud,State Pension Claimant Error,...,16+ Economic Inactivity Rate,16-64 Population,16-64 Total Activity Level,16-64 Employment Level,16-64 Unemployment Level,16-64 Economically Inactive Level,16-64 Economic Activity Rate,16-64 Employment Rate,16-64 Unemployment Rate,16-64 Economic Inactivity Rate
Year,,,,,,,,,,,,,,,,,,,,,
2025,2.2,0.7,0.4,3.3,8.0,0.9,0.8,9.7,w,0.1,...,36.191613,4.330048e+07,3.419484e+07,3.251061e+07,1.684239e+06,9.105636e+06,78.970797,75.081467,4.924607,21.029203
2024,2.7,0.6,0.3,3.6,10.8,0.8,0.7,12.4,0.1,0.1,...,36.878435,4.298149e+07,3.361839e+07,3.213972e+07,1.478670e+06,9.363106e+06,78.215342,74.775176,4.398237,21.784658
2023,2.7,0.6,0.3,3.6,11.4,0.7,0.6,12.7,w,0.1,...,36.904468,4.256827e+07,3.330745e+07,3.191533e+07,1.392125e+06,9.260815e+06,78.245552,74.975208,4.179604,21.754448
2022,3.0,0.7,0.3,4.0,13.0,1.0,0.7,14.7,0,0.1,...,37.008345,4.212816e+07,3.291196e+07,3.163684e+07,1.275122e+06,9.216198e+06,78.123309,75.096694,3.873985,21.876691
2021,2.9,0.6,0.4,3.9,12.8,0.9,0.9,14.5,0,0.1,...,36.801157,4.179978e+07,3.276337e+07,3.127895e+07,1.484415e+06,9.036413e+06,78.381734,74.830055,4.531172,21.618266